# Generated by Django 3.2 on 2026-10-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Objeto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descrición')),
                ('entregado', models.BooleanField(default=False, verbose_name='Entregado')),
            ],
        ),
    ]
